// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2MSZLyKYRTe1oV0BZy0Wgm1mp0OGq4cs',
    appId: '1:663318933578:web:43ca2d33bff1ec9dbf36b3',
    messagingSenderId: '663318933578',
    projectId: 'nest-d9d62',
    authDomain: 'nest-d9d62.firebaseapp.com',
    storageBucket: 'nest-d9d62.firebasestorage.app',
    measurementId: 'G-N0D6DS47PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEJLdANDTDvIg1tArPAGDwkRDdhfw6Yew',
    appId: '1:663318933578:android:8e310ebfc6ab49b3bf36b3',
    messagingSenderId: '663318933578',
    projectId: 'nest-d9d62',
    storageBucket: 'nest-d9d62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1-4lqJpVDesWK37OtDVH3-t81tINw3PA',
    appId: '1:663318933578:ios:292aac522fc61707bf36b3',
    messagingSenderId: '663318933578',
    projectId: 'nest-d9d62',
    storageBucket: 'nest-d9d62.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1-4lqJpVDesWK37OtDVH3-t81tINw3PA',
    appId: '1:663318933578:ios:292aac522fc61707bf36b3',
    messagingSenderId: '663318933578',
    projectId: 'nest-d9d62',
    storageBucket: 'nest-d9d62.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2MSZLyKYRTe1oV0BZy0Wgm1mp0OGq4cs',
    appId: '1:663318933578:web:4b5f8171ab1df25bbf36b3',
    messagingSenderId: '663318933578',
    projectId: 'nest-d9d62',
    authDomain: 'nest-d9d62.firebaseapp.com',
    storageBucket: 'nest-d9d62.firebasestorage.app',
    measurementId: 'G-YMXHP2MNYK',
  );
}
